import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { Suspense } from "react";
import Loading from "./loading";
import Image from "next/image";

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<Script
					crossOrigin="anonymous"
					src="//unpkg.com/react-scan/dist/auto.global.js"
				/>
			</head>
			<body className={`${inter.variable} antialiased`}>
				<div className="flex min-h-svh w-full justify-center items-center p-6">
					<div className="w-full max-w-[600px] space-y-6">
						<header className="flex flex-col items-center gap-6">
							<Image
								src="/esports-logo-white.webp"
								alt="OTSU Esports Logo"
								width={140}
								height={188}
								priority
							/>
							<h1 className="text-3xl font-bold text-center">
								OTSU Esports
								<br />
								Arena Booking Portal
							</h1>
						</header>
						<Suspense fallback={<Loading />}>{children}</Suspense>
					</div>
				</div>
			</body>
		</html>
	);
}
