import type { Metadata } from "next";
import { Teko, Rubik } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { Suspense } from "react";
import Loading from "./loading";
import Image from "next/image";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeToggleButton } from "@/components/theme-toggle-button";

const teko = Teko({
	variable: "--font-teko",
	subsets: ["latin"],
});

const rubik = Rubik({
	variable: "--font-rubik",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<head>
				<Script
					crossOrigin="anonymous"
					src="//unpkg.com/react-scan/dist/auto.global.js"
				/>
			</head>
			<body className={`${teko.variable} ${rubik.variable} antialiased`}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<div className="relative px-6 py-12 w-full max-w-lg mx-auto space-y-12">
						<ThemeToggleButton className="absolute right-6 top-6 cursor-pointer" />
						<header className="flex flex-col items-center gap-6">
							<Image
								src="/esports-logo-colour.png"
								alt="OTSU Esports Logo"
								width={150}
								height={188}
								priority
							/>
							<h1 className="text-5xl font-bold text-center">
								OTSU Esports
								<br />
								Arena Booking Portal
							</h1>
						</header>
						<Suspense fallback={<Loading />}>{children}</Suspense>
					</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
